development:
  mysql41: 9313
  max_matches: 10000
  min_infix_len: 3
  config_file: "./config/development.sphinx.conf"
  searchd_log_file: "./log/searchd.log"
  query_log_file: "./log/searchd.query.log"
  pid_file: "./log/searchd.development.pid"
  bin_path: "/usr/local/bin"
  searchd_binary_name: "searchd"
  indexer_binary_name: "sphinx-indexer"